### ISSUE TITLE
Project restructure

### ISSUE THREAD

**Issue by alxkzmn** [zkmopro/flutter-app#3]
IMHO we don't need to maintain a separate plugin repository for the following reasons:

- The plugin will never be published as a standalone on https://pub.dev/ because it is not "universal". Any Flutter app that is using Mopro will have to fork the plugin template code, generate their own platform libraries and customize the plugin
- The customized plugin code and the app will most likely be placed side-by-side in the file system directories, with the app referencing the plugin by path. I think that a mobile dev would chose to maintain them in a monorepo and reference the plugin from the app by relative path (as it is currently done in [example/pubspec.yaml](https://github.com/zkmopro/flutter-app/blob/3d14f5ded2aa09c2e705fdcce46a879b4d6c1356/example/pubspec.yaml#L26))

I see the following solution:
- Restructure the project to have the `app` and the plugin side-by-side (`app` would be the `example` renamed);
- Delete the https://github.com/zkmopro/flutter-plugin repo.

@vivianjeng what do you think?

**Comment by vivianjeng** [comment]
Yes I totally agree with this!

**Comment by alxkzmn** [comment]
Will implement as soon as https://github.com/zkmopro/flutter-app/pull/2 is merged
